/*
 * Host-side simulation harness.
 * This program compiles on macOS/Linux and drives the actual C logic
 * (including PumpService demand handling + state machine) with data
 * generated from the Python plant model.
 *
 * We link real service code (pump_service.c, pump_demand, etc.) where possible
 * so the simulation exercises the same decision paths as the firmware.
 */

#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "fixed_math.h"
#include "flow_analyzer_core.h"
#include "flow_processor.h"
#include "host_shims.h"
#include "pump/flow_stabilization_contract.h"
#include "pump/pump_demand.h"
#include "pump_state_machine.h"

/* Shim note: flow_event_chan is zbus-only (firmware); host_sim demonstrates
 * equivalent using direct contract_res (and simulates lightweight flow_event
 * concept for wd assertions). Per PR2: reorder to call contract (with conceptual
 * pump_on from SM) first, wire plateau_detected + good/demand from contract_res
 * into demand, cover first plateau -> turn_on(>0), good periods (no spurious
 * demand), watchdog on drop via the gap checks + contract(0) path.
 */

/*
 * Flexible loader for plant-generated data.
 *
 * Supported formats:
 *   - Modern CSV from model/plant/generate_pulse_train.py:
 *       time_s,period_us
 *       0.00,10000000
 *       ...
 *   - Simple space or comma separated (t [flow] period)
 *   - Legacy 3-column format
 */
static int load_pulses(const char *filename, double **times, double **flows,
                       int64_t **periods, int *count) {
  FILE *f = fopen(filename, "r");
  if (!f) {
    perror("fopen");
    return -1;
  }

  char line[256];
  int capacity = 2048;
  *times = malloc(capacity * sizeof(double));
  *flows = malloc(capacity * sizeof(double));
  *periods = malloc(capacity * sizeof(int64_t));
  *count = 0;

  bool header_skipped = false;

  while (fgets(line, sizeof(line), f)) {
    /* Skip empty lines and comments */
    if (line[0] == '\n' || line[0] == '#' || line[0] == '\r')
      continue;

    /* Skip CSV header if present */
    if (!header_skipped) {
      if (strstr(line, "time_s") || strstr(line, "period_us") ||
          strstr(line, "time,")) {
        header_skipped = true;
        continue;
      }
    }

    /* Make parsing robust: turn first comma into space so we can use
     * normal whitespace scanning. This handles both "a,b" and "a b".
     */
    /* Very robust parsing using strtod / strtoll */
    char *p = line;
    double t = strtod(p, &p);
    while (*p && (*p == ',' || *p == ' ' || *p == '\t'))
      p++;
    double maybe_flow = strtod(p, &p);
    while (*p && (*p == ',' || *p == ' ' || *p == '\t'))
      p++;
    long long per = strtoll(p, NULL, 10);

    /* Heuristic: if we only got two numbers and the second is large, treat it
     * as period */
    if (per == 0 && maybe_flow > 100) {
      per = (long long)maybe_flow;
      maybe_flow = 0.0;
    }

    double flow = maybe_flow;

    if (per > 0) {
      if (*count >= capacity) {
        capacity *= 2;
        *times = realloc(*times, capacity * sizeof(double));
        *flows = realloc(*flows, capacity * sizeof(double));
        *periods = realloc(*periods, capacity * sizeof(int64_t));
      }
      (*times)[*count] = t;
      (*flows)[*count] = flow;
      (*periods)[*count] = (int64_t)per;
      (*count)++;
    }
  }
  fclose(f);
  return 0;
}

/* ------------------------------------------------------------------
 * Event-driven pulse simulation helpers
 * ------------------------------------------------------------------ */

/* Lookup the instantaneous period at a given simulated time.
 * Uses simple step (nearest previous sample). Good enough for now.
 */
static int64_t get_period_at_time(double t, const double *times,
                                  const int64_t *periods, int n) {
  if (n <= 0)
    return 10000000LL;

  if (t <= times[0])
    return periods[0];

  for (int i = 1; i < n; i++) {
    if (t < times[i]) {
      return periods[i - 1];
    }
  }
  return periods[n - 1];
}

/* Convert period to approximate flow (for diagnostics) */
static double period_to_flow(int64_t per) {
  if (per <= 0)
    return 0.0;
  return 60e6 / (double)per / 450.0;
}

static void print_usage(const char *prog) {
  printf("Usage: %s [trace_file.csv]\n\n", prog);
  printf("Host simulation of the water pump firmware logic.\n");
  printf("It runs the *real* flow_processor.c + pump_state_machine.c\n");
  printf("against pulse period traces generated by the Python FlowPlant "
         "model.\n\n");
  printf("Recommended workflow on macOS:\n");
  printf("  1. cd model/plant\n");
  printf("  2. python generate_pulse_train.py --scenario watering \\\n");
  printf("        --output-csv ../../model/sim/my_trace.csv\n");
  printf("  3. cd ../sim\n");
  printf("  4. make && ./host_sim my_trace.csv\n\n");
  printf("The loader accepts CSV with 'time_s,period_us' (preferred)\n");
  printf("or simple space/comma separated data.\n");
}

int main(int argc, char **argv) {
  if (argc > 1 &&
      (strcmp(argv[1], "-h") == 0 || strcmp(argv[1], "--help") == 0)) {
    print_usage(argv[0]);
    return 0;
  }

  const char *filename = (argc > 1) ? argv[1] : "plant_trace.csv";

  double *times = NULL;
  double *flows = NULL;
  int64_t *periods = NULL;
  int n = 0;

  if (load_pulses(filename, &times, &flows, &periods, &n) != 0) {
    fprintf(stderr, "Failed to load %s\n\n", filename);
    print_usage(argv[0]);
    return 1;
  }

  printf("Loaded %d samples from %s\n\n", n, filename);

  /* Initialize modules exactly like the firmware */
  struct flow_processor_ctx fproc;
  flow_processor_init(&fproc, 5);

  /* Pure flow analysis simulation - pump logic disabled for now */
  float max_flow_seen = 0.0f;

  /* If the CSV only contained time+period (the common case from the plant
   * model), back-fill the flow array with computed L/min values so the printed
   * "flow" column and summary statistics are actually meaningful.
   */
  bool flows_were_all_zero = true;
  for (int i = 0; i < n; i++) {
    if (flows[i] > 0.001) {
      flows_were_all_zero = false;
      break;
    }
  }
  if (flows_were_all_zero) {
    for (int i = 0; i < n; i++) {
      int64_t per = periods[i];
      if (per > 0 && per < 100000000) {
        flows[i] = 60e6 / (double)per / 450.0; /* L/min using 450 pulses/L */
      }
    }
  }

  /* =====================================================================
   * FAITHFUL REPRODUCTION OF ORIGINAL FLOW STABILIZATION CONTRACT
   * Now delegated to the pure reusable module (single source of truth).
   *
   * The contract module implements exactly the original master branch rules:
   *   - INITIAL_K (2.0) while pump off, NORMAL_K (3.0) while on
   *   - First sample after reset = false
   *   - Buffer fill + calibration + consecutive diff_count required
   *   - Explicit analyzer reset after every confirmed plateau
   *   - 1.5x dynamic watchdog while "on"
   *   - Demand only on significant flow (prevents acting on zero-flow idle
   * stability)
   * ===================================================================== */

  struct flow_contract_state contract;
  flow_contract_init(&contract);

  int plateau_events = 0;
  int watchdog_timeouts = 0;

  /* Simulate the same state that the real PumpService maintains */
  enum pump_sm_state current_sm_state = PUMP_SM_STATE_OFF;
  bool pump_on = pump_sm_is_active(current_sm_state);

  const int64_t NO_PULSE_THRESHOLD_US =
      3000000; /* > 3s period = effectively no flow/pulses */

  printf(" t(s)    flow     raw(us)    filt(us)  diff  noise     K   "
         "phase/status\n");
  printf("---------------------------------------------------------------------"
         "-------\n");

  /* =====================================================================
   * EVENT-DRIVEN PULSE SIMULATION (much closer to real firmware)
   *
   * Instead of processing every dense CSV row, we simulate actual
   * pulse arrival times based on instantaneous flow from the trace.
   *
   * - When flow is healthy, pulses arrive at rate dictated by the period.
   * - When the faucet closes and flow collapses, the time to the next
   *   real pulse becomes very large → the 1.5x watchdog naturally fires.
   * - Zero flow = no pulse events at all (exactly like the real YF-S201C).
   * ===================================================================== */

  double sim_time = 0.0;
  double last_pulse_time = 0.0;
  double total_trace_time = (n > 0) ? times[n - 1] : 0.0;

  while (sim_time <
         total_trace_time + 5.0) { /* small overrun to allow final watchdog */
    /* Query instantaneous period at current simulated time */
    int64_t per = get_period_at_time(sim_time, times, periods, n);
    double flow = period_to_flow(per);

    if (flow > max_flow_seen)
      max_flow_seen = (float)flow;

    bool is_real_pulse = (per > 0 && per < NO_PULSE_THRESHOLD_US);

    /* If pump is on and we're in a no-pulse region, check watchdog starvation
     * (simulates armed k_timer expiry + wd_work contract(now,0) + flow_event)
     */
    if (pump_on && !is_real_pulse) {
      double gap = sim_time - last_pulse_time;
      double wd = (contract.last_plateau_period_us * 1.5) / 1000000.0;

      if (contract.last_plateau_period_us > 0 && gap > wd) {
        printf("%6.2f  %6.2f  %10lld  %10lld   ---  ------  ---  1.5x WATCHDOG "
               "(no pulse for %.2fs) -> PUMP OFF + RESET\n",
               sim_time, flow, per, per, gap);

        /* Exercise contract gap path directly (equiv to wd_work_handler contract(0)) */
        (void)flow_contract_process_sample(&contract, 0, 0, sim_time, true);
        watchdog_timeouts++;  /* we decided gap fire; contract did internal reset */
        /* contract already reset inside + set its pump_is_on=false */
        current_sm_state = PUMP_SM_STATE_OFF;
        pump_on = false;
        /* Do not deliver a pulse — none arrived */
        continue;
      }
    }

    /* If flow is effectively zero, we will not schedule real pulses.
     * Just advance time a bit and let the watchdog logic above handle it
     * on the next iteration if the pump is still on.
     */
    if (!is_real_pulse) {
      /* Jump forward in larger steps when no pulses are expected */
      sim_time += 0.1;
      continue;
    }

    /* Compute time of next pulse arrival */
    double inter_pulse_s = per / 1000000.0;
    double next_pulse_time = sim_time + inter_pulse_s;

    /* Before "delivering" the pulse, check if watchdog would have fired */
    if (pump_on && contract.last_plateau_period_us > 0) {
      double gap_to_next = next_pulse_time - last_pulse_time;
      double wd = (contract.last_plateau_period_us * 1.5) / 1000000.0;

      if (gap_to_next > wd) {
        printf("%6.2f  %6.2f  %10lld  %10lld   ---  ------  ---  1.5x WATCHDOG "
               "(gap=%.2fs) -> PUMP OFF + RESET\n",
               sim_time, flow, per, per, gap_to_next);

        /* Exercise contract gap path (equiv of timer work) */
        (void)flow_contract_process_sample(&contract, 0, 0, sim_time, true);
        watchdog_timeouts++;  /* decided to fire */
        current_sm_state = PUMP_SM_STATE_OFF;
        pump_on = false;
        continue;
      }
    }

    /* Advance simulated time to the actual pulse arrival */
    sim_time = next_pulse_time;

    /* Deliver the pulse to the real logic (exactly like a real ISR would) */
    int64_t filtered = flow_processor_filter_period(&fproc, per);

    float sim_rate = (filtered > 0) ? (60e6f / (float)filtered / 450.0f) : 0.0f;
    fixed_t rate_fixed = fixed_from_float(sim_rate);

    /* Conceptual pump_on from local SM (before this pulse's demand) for contract K */
    bool conceptual_pump_on = pump_sm_is_active(current_sm_state);
    bool was_active_for_demand = conceptual_pump_on;

    /* Feed contract FIRST (with conceptual on) so we get authoritative
     * plateau_confirmed / demand_event / good_period_captured / suggested / wd .
     * This wires the real contract result into demand (for Phase A first plateau
     * demand + >0 period handoff) and simulates flow_event via contract_res. */
    struct flow_contract_result contract_res = flow_contract_process_sample(
        &contract, rate_fixed, per, sim_time, conceptual_pump_on);

    if (contract_res.plateau_confirmed)
      plateau_events++;
    if (contract_res.watchdog_timeout)
      watchdog_timeouts++;

    /* Build sim_flow using contract result (PR2 fidelity) */
    struct flow_sample sim_flow = {
        .rate = rate_fixed,
        .timestamp = (uint64_t)(sim_time * 1000),
        .sequence = 0, /* not important for sim */
        .valid = (per > 0),
        .plateau_detected = contract_res.plateau_confirmed,
        .period_us = per,
    };

    struct pump_demand_input in = {.flow = &sim_flow,
                                   .timer = NULL}; /* .timer pure for future */
    struct pump_demand_result res;

    pump_demand_evaluate(&in, current_sm_state, &res);

    enum pump_sm_state next_state =
        pump_sm_process_event(current_sm_state, res.recommended_event);

    bool state_changed = (next_state != current_sm_state);
    current_sm_state = next_state;
    pump_on = pump_sm_is_active(current_sm_state);

    if (state_changed) {
      const char *reason = res.reason_str ? res.reason_str : "none";
      printf("%6.2f  %6.2f  %10lld  %10lld   ---  ------  ---  [PUMP SM] %s -> "
             "%s (reason=%s)\n",
             sim_time, flow, per, filtered,
             pump_sm_state_to_str(
                 current_sm_state), /* note: may need to handle if not linked */
             pump_sm_state_to_str(next_state), reason);
      if (pump_on && res.updated_plateau_period_us > 0) {
        printf("          >>> turn_on(>0) with period=%lld us (Phase A handoff or refresh)\n",
               res.updated_plateau_period_us);
      }
    }

    const char *phase = pump_on ? "RUN" : "OFF";

    /* Simulate lightweight flow_event for wd (direct from contract) */
    if (contract_res.watchdog_timeout) {
      /* conceptual flow_event */
      printf("%6.2f  %6.2f  %10lld  %10lld   ---  ------  ---  1.5x WATCHDOG "
             "(%.3fs) -> conceptual PUMP OFF + RESET\n",
             sim_time, flow, per, filtered,
             (double)contract_res.suggested_next_timeout_us / 1000000.0);
    } else if (contract_res.plateau_confirmed) {
      if (res.recommended_event == PUMP_SM_EVENT_PLATEAU_DETECTED &&
          !was_active_for_demand ) {
        printf(
            "%6.2f  %6.2f  %10lld  %10lld   %d/%d  %6.4f  %.1f  %s  FIRST "
            "SIGNIFICANT PLATEAU -> DEMAND (would turn pump ON)  [reset=%d]\n",
            sim_time, flow, per, filtered, contract_res.diff_count, 2,
            fixed_to_float(contract_res.noise_std),
            fixed_to_float(contract_res.k_used), phase,
            contract_res.analyzer_was_reset ? 1 : 0);

        printf("          >>> FLOW STABILIZATION GATE PASSED (off->on at "
               "t=%.2fs, period=%lld us)\n",
               sim_time, contract.last_plateau_period_us);

      } else if (contract_res.good_period_captured) {
        printf("%6.2f  %6.2f  %10lld  %10lld   %d/%d  %6.4f  %.1f  %s  Good "
               "stable period captured (watchdog timing updated)  [reset=%d]\n",
               sim_time, flow, per, filtered, contract_res.diff_count, 2,
               fixed_to_float(contract_res.noise_std),
               fixed_to_float(contract_res.k_used), phase,
               contract_res.analyzer_was_reset ? 1 : 0);
      } else {
        printf("%6.2f  %6.2f  %10lld  %10lld   %d/%d  %6.4f  %.1f  %s  plateau "
               "(low/zero flow, ignored)  [reset=%d]\n",
               sim_time, flow, per, filtered, contract_res.diff_count, 2,
               fixed_to_float(contract_res.noise_std),
               fixed_to_float(contract_res.k_used), phase,
               contract_res.analyzer_was_reset ? 1 : 0);
      }
    } else if ((int)(sim_time * 50) % 5 == 0) {
      const char *note = "";
      if (contract_res.diff_count > 0) {
        note = (contract_res.noise_std > 0 ? " (counting)" : " (calibrating)");
      }
      printf("%6.2f  %6.2f  %10lld  %10lld   %d/%d  %6.4f  %.1f  %s%s\n",
             sim_time, flow, per, filtered, contract_res.diff_count, 2,
             fixed_to_float(contract_res.noise_std),
             fixed_to_float(contract_res.k_used), phase, note);
    }

    last_pulse_time = sim_time;
  }

  /* The event-driven loop above should naturally produce watchdog events
   * when the faucet closes and pulses stop arriving. The old artificial
   * gap injection has been removed because it is no longer required.
   */

  double total_time = (n > 0) ? times[n - 1] : 0.0;

  free(times);
  free(flows);
  free(periods);

  printf("\n=== Faithful Flow Stabilization Summary (original contract) ===\n");
  printf("Simulated duration          : %.1f seconds\n", total_time);
  printf("Total samples processed     : %d\n", n);
  printf("Confirmed plateau events    : %d\n", plateau_events);
  printf("Watchdog timeouts (1.5x)    : %d\n", watchdog_timeouts);
  printf("Analyzer resets performed   : (see contract internal state)\n");
  printf("Peak flow observed          : %.2f L/min\n", max_flow_seen);
  printf("Peak simulated pump state   : %s\n",
         pump_sm_is_active(current_sm_state) ? "ON at end" : "OFF at end");
  printf("Note: Uses real core + INITIAL_K=2.0 (off) / NORMAL_K=3.0 (on) + "
         "explicit reset after every plateau + 1.5x pulse watchdog.\n");
  printf(
      "====================================================================\n");

  /* PR2: 20s scenario coverage (first plateau demand, good no spurious, wd on drop,
   * turn_on(>0) via updated_plateau always, flow_event equiv via contract wd).
   * Run with model/sim/20s_realistic_trace.csv or plant_trace_realistic.csv to exercise. */
  if (strstr(filename, "20s") || strstr(filename, "realistic") || n > 1000) {
    printf("20s scenario checks: plateau=%d wd=%d (expect >=1 each; first plateau "
           "demand + turn_on(>0) + final wd off visible in trace above)\n",
           plateau_events, watchdog_timeouts);
    if (watchdog_timeouts < 1) {
      printf("  [note] 20s watchdog not observed (may depend on trace end gaps)\n");
    }
    if (plateau_events < 1) {
      printf("  [note] no plateau events in 20s trace?\n");
    }
  }

  return 0;
}
